services:
  acsm-bot:
    build: .
    container_name: acsm-bot
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CALIBRE_CONFIG_DIRECTORY=/config
    volumes:
      - ./config:/config
      - ./output:/output
    ports:
      - "8080:8080"
      - "8082:8082"